// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARf7TL0bSSQYA0cwj-9GqZz7f-yEFPDNs',
    appId: '1:955758912205:web:2676eaeab026fa0a1d3f84',
    messagingSenderId: '955758912205',
    projectId: 'chatapp-33940',
    authDomain: 'chatapp-33940.firebaseapp.com',
    storageBucket: 'chatapp-33940.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV0GCaEyTysZPLC9iKeMsqippcc-CSTMw',
    appId: '1:955758912205:android:7aabc9ea362d2df31d3f84',
    messagingSenderId: '955758912205',
    projectId: 'chatapp-33940',
    storageBucket: 'chatapp-33940.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2p0ZAV8SSevI5GozC79TboOsIiikDEjc',
    appId: '1:955758912205:ios:3001738c901432a61d3f84',
    messagingSenderId: '955758912205',
    projectId: 'chatapp-33940',
    storageBucket: 'chatapp-33940.appspot.com',
    iosClientId: '955758912205-dk8vfae91uinslhmp5g28m6iggghfiee.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2p0ZAV8SSevI5GozC79TboOsIiikDEjc',
    appId: '1:955758912205:ios:9e08d34ff91aa56a1d3f84',
    messagingSenderId: '955758912205',
    projectId: 'chatapp-33940',
    storageBucket: 'chatapp-33940.appspot.com',
    iosClientId: '955758912205-nnauj3j651okufe0tlakf6emscreprg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
